"""Rocket OpenCode runtime package."""

from agent.runtime.adapter import RocketAdapter, apply_verifier, run_with_recovery
from agent.runtime.bootstrap import rocket_bootstrap, sync_opencode_runtime
from agent.runtime.first_launch import (
    BootstrapMarkers,
    BootstrapResult,
    BundledComponents,
    FirstLaunchBootstrap,
    OnboardingPreferences,
    detect_bundled_components,
    registration_status,
)
from agent.runtime.install_mission import (
    InstallMissionRunner,
    InstallMissionVerifier,
    InstallStatus,
    UacProbe,
    WindowsUacProbe,
    install_key_from_mission,
)
from agent.runtime.recovery import (
    RecoveryEngine,
    RecoveryMetrics,
    RecoveryStrategy,
    classify_failure,
    recovery_plan,
)
from agent.runtime.benchmark import (
    BenchmarkReport,
    BenchmarkResult,
    BenchmarkTask,
    ExecOutcome,
    generate_default_suite,
    run_benchmark,
    simulated_executor,
)
from agent.runtime.benchmark_live import RocketAdapterExecutor, run_live_benchmark
from agent.runtime.browser_runtime import (
    BrowserController,
    BrowserRuntime,
    BrowserRuntimeState,
    BrowserWindow,
    WindowsBrowserController,
    get_browser_runtime,
    reset_browser_runtime,
)
from agent.runtime.terminal_bridge import Phase2TerminalBridge, RuntimeTerminalBridge
from agent.runtime.verifier import (
    BluetoothVerifier,
    BrowserVerifier,
    FilesystemVerifier,
    InstallVerifier,
    ProcessVerifier,
    RealityProbe,
    Verdict,
    VerifierSuite,
    WifiVerifier,
    WindowInfo,
    WindowVerifier,
    WindowsRealityProbe,
)

__all__ = [
    "RocketAdapter",
    "apply_verifier",
    "run_with_recovery",
    "Phase2TerminalBridge",
    "RuntimeTerminalBridge",
    "rocket_bootstrap",
    "sync_opencode_runtime",
    "BootstrapMarkers",
    "BootstrapResult",
    "BundledComponents",
    "FirstLaunchBootstrap",
    "OnboardingPreferences",
    "detect_bundled_components",
    "registration_status",
    "InstallMissionRunner",
    "InstallMissionVerifier",
    "InstallStatus",
    "UacProbe",
    "WindowsUacProbe",
    "install_key_from_mission",
    "RecoveryEngine",
    "RecoveryMetrics",
    "RecoveryStrategy",
    "classify_failure",
    "recovery_plan",
    "BenchmarkReport",
    "BenchmarkResult",
    "BenchmarkTask",
    "ExecOutcome",
    "generate_default_suite",
    "run_benchmark",
    "simulated_executor",
    "RocketAdapterExecutor",
    "run_live_benchmark",
    "BrowserController",
    "BrowserRuntime",
    "BrowserRuntimeState",
    "BrowserWindow",
    "WindowsBrowserController",
    "get_browser_runtime",
    "reset_browser_runtime",
    "BluetoothVerifier",
    "BrowserVerifier",
    "FilesystemVerifier",
    "InstallVerifier",
    "ProcessVerifier",
    "RealityProbe",
    "Verdict",
    "VerifierSuite",
    "WifiVerifier",
    "WindowInfo",
    "WindowVerifier",
    "WindowsRealityProbe",
]
